// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

package orwell.messages;

public final class Robot {
  private Robot() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RobotStateOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional double life = 1;
    boolean hasLife();
    double getLife();
    
    // optional group Move = 2 {
    boolean hasMove();
    orwell.messages.Robot.RobotState.Move getMove();
    
    // optional bool active = 3 [default = true];
    boolean hasActive();
    boolean getActive();
  }
  public static final class RobotState extends
      com.google.protobuf.GeneratedMessageLite
      implements RobotStateOrBuilder {
    // Use RobotState.newBuilder() to construct.
    private RobotState(Builder builder) {
      super(builder);
    }
    private RobotState(boolean noInit) {}
    
    private static final RobotState defaultInstance;
    public static RobotState getDefaultInstance() {
      return defaultInstance;
    }
    
    public RobotState getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public interface MoveOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {
      
      // optional double left = 1;
      boolean hasLeft();
      double getLeft();
      
      // optional double right = 2;
      boolean hasRight();
      double getRight();
    }
    public static final class Move extends
        com.google.protobuf.GeneratedMessageLite
        implements MoveOrBuilder {
      // Use Move.newBuilder() to construct.
      private Move(Builder builder) {
        super(builder);
      }
      private Move(boolean noInit) {}
      
      private static final Move defaultInstance;
      public static Move getDefaultInstance() {
        return defaultInstance;
      }
      
      public Move getDefaultInstanceForType() {
        return defaultInstance;
      }
      
      private int bitField0_;
      // optional double left = 1;
      public static final int LEFT_FIELD_NUMBER = 1;
      private double left_;
      public boolean hasLeft() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getLeft() {
        return left_;
      }
      
      // optional double right = 2;
      public static final int RIGHT_FIELD_NUMBER = 2;
      private double right_;
      public boolean hasRight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public double getRight() {
        return right_;
      }
      
      private void initFields() {
        left_ = 0D;
        right_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;
        
        memoizedIsInitialized = 1;
        return true;
      }
      
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeDouble(1, left_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, right_);
        }
      }
      
      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;
      
        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, left_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, right_);
        }
        memoizedSerializedSize = size;
        return size;
      }
      
      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }
      
      public static orwell.messages.Robot.RobotState.Move parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data).buildParsed();
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return newBuilder().mergeFrom(data, extensionRegistry)
                 .buildParsed();
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      public static orwell.messages.Robot.RobotState.Move parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static orwell.messages.Robot.RobotState.Move parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Builder builder = newBuilder();
        if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
          return builder.buildParsed();
        } else {
          return null;
        }
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input).buildParsed();
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return newBuilder().mergeFrom(input, extensionRegistry)
                 .buildParsed();
      }
      
      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(orwell.messages.Robot.RobotState.Move prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }
      
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            orwell.messages.Robot.RobotState.Move, Builder>
          implements orwell.messages.Robot.RobotState.MoveOrBuilder {
        // Construct using orwell.messages.Robot.RobotState.Move.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }
        
        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }
        
        public Builder clear() {
          super.clear();
          left_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000001);
          right_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }
        
        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }
        
        public orwell.messages.Robot.RobotState.Move getDefaultInstanceForType() {
          return orwell.messages.Robot.RobotState.Move.getDefaultInstance();
        }
        
        public orwell.messages.Robot.RobotState.Move build() {
          orwell.messages.Robot.RobotState.Move result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }
        
        private orwell.messages.Robot.RobotState.Move buildParsed()
            throws com.google.protobuf.InvalidProtocolBufferException {
          orwell.messages.Robot.RobotState.Move result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(
              result).asInvalidProtocolBufferException();
          }
          return result;
        }
        
        public orwell.messages.Robot.RobotState.Move buildPartial() {
          orwell.messages.Robot.RobotState.Move result = new orwell.messages.Robot.RobotState.Move(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.left_ = left_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.right_ = right_;
          result.bitField0_ = to_bitField0_;
          return result;
        }
        
        public Builder mergeFrom(orwell.messages.Robot.RobotState.Move other) {
          if (other == orwell.messages.Robot.RobotState.Move.getDefaultInstance()) return this;
          if (other.hasLeft()) {
            setLeft(other.getLeft());
          }
          if (other.hasRight()) {
            setRight(other.getRight());
          }
          return this;
        }
        
        public final boolean isInitialized() {
          return true;
        }
        
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          while (true) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                
                return this;
              default: {
                if (!parseUnknownField(input, extensionRegistry, tag)) {
                  
                  return this;
                }
                break;
              }
              case 9: {
                bitField0_ |= 0x00000001;
                left_ = input.readDouble();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                right_ = input.readDouble();
                break;
              }
            }
          }
        }
        
        private int bitField0_;
        
        // optional double left = 1;
        private double left_ ;
        public boolean hasLeft() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        public double getLeft() {
          return left_;
        }
        public Builder setLeft(double value) {
          bitField0_ |= 0x00000001;
          left_ = value;
          
          return this;
        }
        public Builder clearLeft() {
          bitField0_ = (bitField0_ & ~0x00000001);
          left_ = 0D;
          
          return this;
        }
        
        // optional double right = 2;
        private double right_ ;
        public boolean hasRight() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        public double getRight() {
          return right_;
        }
        public Builder setRight(double value) {
          bitField0_ |= 0x00000002;
          right_ = value;
          
          return this;
        }
        public Builder clearRight() {
          bitField0_ = (bitField0_ & ~0x00000002);
          right_ = 0D;
          
          return this;
        }
        
        // @@protoc_insertion_point(builder_scope:orwell.messages.RobotState.Move)
      }
      
      static {
        defaultInstance = new Move(true);
        defaultInstance.initFields();
      }
      
      // @@protoc_insertion_point(class_scope:orwell.messages.RobotState.Move)
    }
    
    private int bitField0_;
    // optional double life = 1;
    public static final int LIFE_FIELD_NUMBER = 1;
    private double life_;
    public boolean hasLife() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public double getLife() {
      return life_;
    }
    
    // optional group Move = 2 {
    public static final int MOVE_FIELD_NUMBER = 2;
    private orwell.messages.Robot.RobotState.Move move_;
    public boolean hasMove() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public orwell.messages.Robot.RobotState.Move getMove() {
      return move_;
    }
    
    // optional bool active = 3 [default = true];
    public static final int ACTIVE_FIELD_NUMBER = 3;
    private boolean active_;
    public boolean hasActive() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public boolean getActive() {
      return active_;
    }
    
    private void initFields() {
      life_ = 0D;
      move_ = orwell.messages.Robot.RobotState.Move.getDefaultInstance();
      active_ = true;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, life_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeGroup(2, move_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, active_);
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, life_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeGroupSize(2, move_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, active_);
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static orwell.messages.Robot.RobotState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static orwell.messages.Robot.RobotState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static orwell.messages.Robot.RobotState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static orwell.messages.Robot.RobotState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static orwell.messages.Robot.RobotState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static orwell.messages.Robot.RobotState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static orwell.messages.Robot.RobotState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static orwell.messages.Robot.RobotState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static orwell.messages.Robot.RobotState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static orwell.messages.Robot.RobotState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(orwell.messages.Robot.RobotState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          orwell.messages.Robot.RobotState, Builder>
        implements orwell.messages.Robot.RobotStateOrBuilder {
      // Construct using orwell.messages.Robot.RobotState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        life_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        move_ = orwell.messages.Robot.RobotState.Move.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        active_ = true;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public orwell.messages.Robot.RobotState getDefaultInstanceForType() {
        return orwell.messages.Robot.RobotState.getDefaultInstance();
      }
      
      public orwell.messages.Robot.RobotState build() {
        orwell.messages.Robot.RobotState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private orwell.messages.Robot.RobotState buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        orwell.messages.Robot.RobotState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public orwell.messages.Robot.RobotState buildPartial() {
        orwell.messages.Robot.RobotState result = new orwell.messages.Robot.RobotState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.life_ = life_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.move_ = move_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.active_ = active_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(orwell.messages.Robot.RobotState other) {
        if (other == orwell.messages.Robot.RobotState.getDefaultInstance()) return this;
        if (other.hasLife()) {
          setLife(other.getLife());
        }
        if (other.hasMove()) {
          mergeMove(other.getMove());
        }
        if (other.hasActive()) {
          setActive(other.getActive());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              life_ = input.readDouble();
              break;
            }
            case 19: {
              orwell.messages.Robot.RobotState.Move.Builder subBuilder = orwell.messages.Robot.RobotState.Move.newBuilder();
              if (hasMove()) {
                subBuilder.mergeFrom(getMove());
              }
              input.readGroup(2, subBuilder, extensionRegistry);
              setMove(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              active_ = input.readBool();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional double life = 1;
      private double life_ ;
      public boolean hasLife() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public double getLife() {
        return life_;
      }
      public Builder setLife(double value) {
        bitField0_ |= 0x00000001;
        life_ = value;
        
        return this;
      }
      public Builder clearLife() {
        bitField0_ = (bitField0_ & ~0x00000001);
        life_ = 0D;
        
        return this;
      }
      
      // optional group Move = 2 {
      private orwell.messages.Robot.RobotState.Move move_ = orwell.messages.Robot.RobotState.Move.getDefaultInstance();
      public boolean hasMove() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public orwell.messages.Robot.RobotState.Move getMove() {
        return move_;
      }
      public Builder setMove(orwell.messages.Robot.RobotState.Move value) {
        if (value == null) {
          throw new NullPointerException();
        }
        move_ = value;
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setMove(
          orwell.messages.Robot.RobotState.Move.Builder builderForValue) {
        move_ = builderForValue.build();
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeMove(orwell.messages.Robot.RobotState.Move value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            move_ != orwell.messages.Robot.RobotState.Move.getDefaultInstance()) {
          move_ =
            orwell.messages.Robot.RobotState.Move.newBuilder(move_).mergeFrom(value).buildPartial();
        } else {
          move_ = value;
        }
        
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearMove() {
        move_ = orwell.messages.Robot.RobotState.Move.getDefaultInstance();
        
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      // optional bool active = 3 [default = true];
      private boolean active_ = true;
      public boolean hasActive() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public boolean getActive() {
        return active_;
      }
      public Builder setActive(boolean value) {
        bitField0_ |= 0x00000004;
        active_ = value;
        
        return this;
      }
      public Builder clearActive() {
        bitField0_ = (bitField0_ & ~0x00000004);
        active_ = true;
        
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:orwell.messages.RobotState)
    }
    
    static {
      defaultInstance = new RobotState(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:orwell.messages.RobotState)
  }
  
  public interface VideoOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {
    
    // optional uint32 port = 1;
    boolean hasPort();
    int getPort();
    
    // optional string ip = 2;
    boolean hasIp();
    String getIp();
  }
  public static final class Video extends
      com.google.protobuf.GeneratedMessageLite
      implements VideoOrBuilder {
    // Use Video.newBuilder() to construct.
    private Video(Builder builder) {
      super(builder);
    }
    private Video(boolean noInit) {}
    
    private static final Video defaultInstance;
    public static Video getDefaultInstance() {
      return defaultInstance;
    }
    
    public Video getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    private int bitField0_;
    // optional uint32 port = 1;
    public static final int PORT_FIELD_NUMBER = 1;
    private int port_;
    public boolean hasPort() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public int getPort() {
      return port_;
    }
    
    // optional string ip = 2;
    public static final int IP_FIELD_NUMBER = 2;
    private java.lang.Object ip_;
    public boolean hasIp() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getIp() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          ip_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getIpBytes() {
      java.lang.Object ref = ip_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        ip_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      port_ = 0;
      ip_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, port_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getIpBytes());
      }
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, port_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getIpBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static orwell.messages.Robot.Video parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static orwell.messages.Robot.Video parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static orwell.messages.Robot.Video parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static orwell.messages.Robot.Video parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static orwell.messages.Robot.Video parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static orwell.messages.Robot.Video parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static orwell.messages.Robot.Video parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static orwell.messages.Robot.Video parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static orwell.messages.Robot.Video parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static orwell.messages.Robot.Video parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(orwell.messages.Robot.Video prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          orwell.messages.Robot.Video, Builder>
        implements orwell.messages.Robot.VideoOrBuilder {
      // Construct using orwell.messages.Robot.Video.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        port_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        ip_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public orwell.messages.Robot.Video getDefaultInstanceForType() {
        return orwell.messages.Robot.Video.getDefaultInstance();
      }
      
      public orwell.messages.Robot.Video build() {
        orwell.messages.Robot.Video result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private orwell.messages.Robot.Video buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        orwell.messages.Robot.Video result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public orwell.messages.Robot.Video buildPartial() {
        orwell.messages.Robot.Video result = new orwell.messages.Robot.Video(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.port_ = port_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.ip_ = ip_;
        result.bitField0_ = to_bitField0_;
        return result;
      }
      
      public Builder mergeFrom(orwell.messages.Robot.Video other) {
        if (other == orwell.messages.Robot.Video.getDefaultInstance()) return this;
        if (other.hasPort()) {
          setPort(other.getPort());
        }
        if (other.hasIp()) {
          setIp(other.getIp());
        }
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              
              return this;
            default: {
              if (!parseUnknownField(input, extensionRegistry, tag)) {
                
                return this;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              port_ = input.readUInt32();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              ip_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional uint32 port = 1;
      private int port_ ;
      public boolean hasPort() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public int getPort() {
        return port_;
      }
      public Builder setPort(int value) {
        bitField0_ |= 0x00000001;
        port_ = value;
        
        return this;
      }
      public Builder clearPort() {
        bitField0_ = (bitField0_ & ~0x00000001);
        port_ = 0;
        
        return this;
      }
      
      // optional string ip = 2;
      private java.lang.Object ip_ = "";
      public boolean hasIp() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getIp() {
        java.lang.Object ref = ip_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          ip_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setIp(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        ip_ = value;
        
        return this;
      }
      public Builder clearIp() {
        bitField0_ = (bitField0_ & ~0x00000002);
        ip_ = getDefaultInstance().getIp();
        
        return this;
      }
      void setIp(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        ip_ = value;
        
      }
      
      // @@protoc_insertion_point(builder_scope:orwell.messages.Video)
    }
    
    static {
      defaultInstance = new Video(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:orwell.messages.Video)
  }
  
  
  static {
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
