// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: robot.proto

package orwell.messages;

public final class Robot {
  private Robot() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface RobotStateOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // optional double life = 1;
    /**
     * <code>optional double life = 1;</code>
     */
    boolean hasLife();
    /**
     * <code>optional double life = 1;</code>
     */
    double getLife();

    // optional group Move = 2 {
    /**
     * <code>optional group Move = 2 { ... }</code>
     */
    boolean hasMove();
    /**
     * <code>optional group Move = 2 { ... }</code>
     */
    orwell.messages.Robot.RobotState.Move getMove();

    // optional bool active = 3 [default = true];
    /**
     * <code>optional bool active = 3 [default = true];</code>
     */
    boolean hasActive();
    /**
     * <code>optional bool active = 3 [default = true];</code>
     */
    boolean getActive();

    // optional string rfid = 4 [default = ""];
    /**
     * <code>optional string rfid = 4 [default = ""];</code>
     */
    boolean hasRfid();
    /**
     * <code>optional string rfid = 4 [default = ""];</code>
     */
    java.lang.String getRfid();
    /**
     * <code>optional string rfid = 4 [default = ""];</code>
     */
    com.google.protobuf.ByteString
        getRfidBytes();

    // optional int32 color = 5 [default = -1];
    /**
     * <code>optional int32 color = 5 [default = -1];</code>
     */
    boolean hasColor();
    /**
     * <code>optional int32 color = 5 [default = -1];</code>
     */
    int getColor();
  }
  /**
   * Protobuf type {@code orwell.messages.RobotState}
   *
   * <pre>
   * Notify the state the robot is in (sent while playing)
   * </pre>
   */
  public static final class RobotState extends
      com.google.protobuf.GeneratedMessageLite
      implements RobotStateOrBuilder {
    // Use RobotState.newBuilder() to construct.
    private RobotState(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private RobotState(boolean noInit) {}

    private static final RobotState defaultInstance;
    public static RobotState getDefaultInstance() {
      return defaultInstance;
    }

    public RobotState getDefaultInstanceForType() {
      return defaultInstance;
    }

    private RobotState(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              life_ = input.readDouble();
              break;
            }
            case 19: {
              orwell.messages.Robot.RobotState.Move.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = move_.toBuilder();
              }
              move_ = input.readGroup(2, orwell.messages.Robot.RobotState.Move.PARSER,
                  extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(move_);
                move_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              active_ = input.readBool();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              rfid_ = input.readBytes();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              color_ = input.readInt32();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<RobotState> PARSER =
        new com.google.protobuf.AbstractParser<RobotState>() {
      public RobotState parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RobotState(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<RobotState> getParserForType() {
      return PARSER;
    }

    public interface MoveOrBuilder
        extends com.google.protobuf.MessageLiteOrBuilder {

      // optional double left = 1;
      /**
       * <code>optional double left = 1;</code>
       */
      boolean hasLeft();
      /**
       * <code>optional double left = 1;</code>
       */
      double getLeft();

      // optional double right = 2;
      /**
       * <code>optional double right = 2;</code>
       */
      boolean hasRight();
      /**
       * <code>optional double right = 2;</code>
       */
      double getRight();
    }
    /**
     * Protobuf type {@code orwell.messages.RobotState.Move}
     */
    public static final class Move extends
        com.google.protobuf.GeneratedMessageLite
        implements MoveOrBuilder {
      // Use Move.newBuilder() to construct.
      private Move(com.google.protobuf.GeneratedMessageLite.Builder builder) {
        super(builder);

      }
      private Move(boolean noInit) {}

      private static final Move defaultInstance;
      public static Move getDefaultInstance() {
        return defaultInstance;
      }

      public Move getDefaultInstanceForType() {
        return defaultInstance;
      }

      private Move(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 9: {
                bitField0_ |= 0x00000001;
                left_ = input.readDouble();
                break;
              }
              case 17: {
                bitField0_ |= 0x00000002;
                right_ = input.readDouble();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          makeExtensionsImmutable();
        }
      }
      public static com.google.protobuf.Parser<Move> PARSER =
          new com.google.protobuf.AbstractParser<Move>() {
        public Move parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Move(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<Move> getParserForType() {
        return PARSER;
      }

      private int bitField0_;
      // optional double left = 1;
      public static final int LEFT_FIELD_NUMBER = 1;
      private double left_;
      /**
       * <code>optional double left = 1;</code>
       */
      public boolean hasLeft() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double left = 1;</code>
       */
      public double getLeft() {
        return left_;
      }

      // optional double right = 2;
      public static final int RIGHT_FIELD_NUMBER = 2;
      private double right_;
      /**
       * <code>optional double right = 2;</code>
       */
      public boolean hasRight() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional double right = 2;</code>
       */
      public double getRight() {
        return right_;
      }

      private void initFields() {
        left_ = 0D;
        right_ = 0D;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeDouble(1, left_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeDouble(2, right_);
        }
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(1, left_);
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeDoubleSize(2, right_);
        }
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static orwell.messages.Robot.RobotState.Move parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static orwell.messages.Robot.RobotState.Move parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static orwell.messages.Robot.RobotState.Move parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static orwell.messages.Robot.RobotState.Move parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(orwell.messages.Robot.RobotState.Move prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      /**
       * Protobuf type {@code orwell.messages.RobotState.Move}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageLite.Builder<
            orwell.messages.Robot.RobotState.Move, Builder>
          implements orwell.messages.Robot.RobotState.MoveOrBuilder {
        // Construct using orwell.messages.Robot.RobotState.Move.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          left_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000001);
          right_ = 0D;
          bitField0_ = (bitField0_ & ~0x00000002);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public orwell.messages.Robot.RobotState.Move getDefaultInstanceForType() {
          return orwell.messages.Robot.RobotState.Move.getDefaultInstance();
        }

        public orwell.messages.Robot.RobotState.Move build() {
          orwell.messages.Robot.RobotState.Move result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public orwell.messages.Robot.RobotState.Move buildPartial() {
          orwell.messages.Robot.RobotState.Move result = new orwell.messages.Robot.RobotState.Move(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.left_ = left_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.right_ = right_;
          result.bitField0_ = to_bitField0_;
          return result;
        }

        public Builder mergeFrom(orwell.messages.Robot.RobotState.Move other) {
          if (other == orwell.messages.Robot.RobotState.Move.getDefaultInstance()) return this;
          if (other.hasLeft()) {
            setLeft(other.getLeft());
          }
          if (other.hasRight()) {
            setRight(other.getRight());
          }
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          orwell.messages.Robot.RobotState.Move parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (orwell.messages.Robot.RobotState.Move) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional double left = 1;
        private double left_ ;
        /**
         * <code>optional double left = 1;</code>
         */
        public boolean hasLeft() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional double left = 1;</code>
         */
        public double getLeft() {
          return left_;
        }
        /**
         * <code>optional double left = 1;</code>
         */
        public Builder setLeft(double value) {
          bitField0_ |= 0x00000001;
          left_ = value;
          
          return this;
        }
        /**
         * <code>optional double left = 1;</code>
         */
        public Builder clearLeft() {
          bitField0_ = (bitField0_ & ~0x00000001);
          left_ = 0D;
          
          return this;
        }

        // optional double right = 2;
        private double right_ ;
        /**
         * <code>optional double right = 2;</code>
         */
        public boolean hasRight() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional double right = 2;</code>
         */
        public double getRight() {
          return right_;
        }
        /**
         * <code>optional double right = 2;</code>
         */
        public Builder setRight(double value) {
          bitField0_ |= 0x00000002;
          right_ = value;
          
          return this;
        }
        /**
         * <code>optional double right = 2;</code>
         */
        public Builder clearRight() {
          bitField0_ = (bitField0_ & ~0x00000002);
          right_ = 0D;
          
          return this;
        }

        // @@protoc_insertion_point(builder_scope:orwell.messages.RobotState.Move)
      }

      static {
        defaultInstance = new Move(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:orwell.messages.RobotState.Move)
    }

    private int bitField0_;
    // optional double life = 1;
    public static final int LIFE_FIELD_NUMBER = 1;
    private double life_;
    /**
     * <code>optional double life = 1;</code>
     */
    public boolean hasLife() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double life = 1;</code>
     */
    public double getLife() {
      return life_;
    }

    // optional group Move = 2 {
    public static final int MOVE_FIELD_NUMBER = 2;
    private orwell.messages.Robot.RobotState.Move move_;
    /**
     * <code>optional group Move = 2 { ... }</code>
     */
    public boolean hasMove() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional group Move = 2 { ... }</code>
     */
    public orwell.messages.Robot.RobotState.Move getMove() {
      return move_;
    }

    // optional bool active = 3 [default = true];
    public static final int ACTIVE_FIELD_NUMBER = 3;
    private boolean active_;
    /**
     * <code>optional bool active = 3 [default = true];</code>
     */
    public boolean hasActive() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool active = 3 [default = true];</code>
     */
    public boolean getActive() {
      return active_;
    }

    // optional string rfid = 4 [default = ""];
    public static final int RFID_FIELD_NUMBER = 4;
    private java.lang.Object rfid_;
    /**
     * <code>optional string rfid = 4 [default = ""];</code>
     */
    public boolean hasRfid() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string rfid = 4 [default = ""];</code>
     */
    public java.lang.String getRfid() {
      java.lang.Object ref = rfid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          rfid_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string rfid = 4 [default = ""];</code>
     */
    public com.google.protobuf.ByteString
        getRfidBytes() {
      java.lang.Object ref = rfid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        rfid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional int32 color = 5 [default = -1];
    public static final int COLOR_FIELD_NUMBER = 5;
    private int color_;
    /**
     * <code>optional int32 color = 5 [default = -1];</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional int32 color = 5 [default = -1];</code>
     */
    public int getColor() {
      return color_;
    }

    private void initFields() {
      life_ = 0D;
      move_ = orwell.messages.Robot.RobotState.Move.getDefaultInstance();
      active_ = true;
      rfid_ = "";
      color_ = -1;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, life_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeGroup(2, move_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, active_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getRfidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt32(5, color_);
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, life_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeGroupSize(2, move_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, active_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getRfidBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, color_);
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static orwell.messages.Robot.RobotState parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static orwell.messages.Robot.RobotState parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static orwell.messages.Robot.RobotState parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static orwell.messages.Robot.RobotState parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static orwell.messages.Robot.RobotState parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static orwell.messages.Robot.RobotState parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static orwell.messages.Robot.RobotState parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static orwell.messages.Robot.RobotState parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static orwell.messages.Robot.RobotState parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static orwell.messages.Robot.RobotState parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(orwell.messages.Robot.RobotState prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code orwell.messages.RobotState}
     *
     * <pre>
     * Notify the state the robot is in (sent while playing)
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          orwell.messages.Robot.RobotState, Builder>
        implements orwell.messages.Robot.RobotStateOrBuilder {
      // Construct using orwell.messages.Robot.RobotState.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        life_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        move_ = orwell.messages.Robot.RobotState.Move.getDefaultInstance();
        bitField0_ = (bitField0_ & ~0x00000002);
        active_ = true;
        bitField0_ = (bitField0_ & ~0x00000004);
        rfid_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        color_ = -1;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public orwell.messages.Robot.RobotState getDefaultInstanceForType() {
        return orwell.messages.Robot.RobotState.getDefaultInstance();
      }

      public orwell.messages.Robot.RobotState build() {
        orwell.messages.Robot.RobotState result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public orwell.messages.Robot.RobotState buildPartial() {
        orwell.messages.Robot.RobotState result = new orwell.messages.Robot.RobotState(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.life_ = life_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.move_ = move_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.active_ = active_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.rfid_ = rfid_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.color_ = color_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(orwell.messages.Robot.RobotState other) {
        if (other == orwell.messages.Robot.RobotState.getDefaultInstance()) return this;
        if (other.hasLife()) {
          setLife(other.getLife());
        }
        if (other.hasMove()) {
          mergeMove(other.getMove());
        }
        if (other.hasActive()) {
          setActive(other.getActive());
        }
        if (other.hasRfid()) {
          bitField0_ |= 0x00000008;
          rfid_ = other.rfid_;
          
        }
        if (other.hasColor()) {
          setColor(other.getColor());
        }
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        orwell.messages.Robot.RobotState parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (orwell.messages.Robot.RobotState) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional double life = 1;
      private double life_ ;
      /**
       * <code>optional double life = 1;</code>
       */
      public boolean hasLife() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double life = 1;</code>
       */
      public double getLife() {
        return life_;
      }
      /**
       * <code>optional double life = 1;</code>
       */
      public Builder setLife(double value) {
        bitField0_ |= 0x00000001;
        life_ = value;
        
        return this;
      }
      /**
       * <code>optional double life = 1;</code>
       */
      public Builder clearLife() {
        bitField0_ = (bitField0_ & ~0x00000001);
        life_ = 0D;
        
        return this;
      }

      // optional group Move = 2 {
      private orwell.messages.Robot.RobotState.Move move_ = orwell.messages.Robot.RobotState.Move.getDefaultInstance();
      /**
       * <code>optional group Move = 2 { ... }</code>
       */
      public boolean hasMove() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional group Move = 2 { ... }</code>
       */
      public orwell.messages.Robot.RobotState.Move getMove() {
        return move_;
      }
      /**
       * <code>optional group Move = 2 { ... }</code>
       */
      public Builder setMove(orwell.messages.Robot.RobotState.Move value) {
        if (value == null) {
          throw new NullPointerException();
        }
        move_ = value;

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional group Move = 2 { ... }</code>
       */
      public Builder setMove(
          orwell.messages.Robot.RobotState.Move.Builder builderForValue) {
        move_ = builderForValue.build();

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional group Move = 2 { ... }</code>
       */
      public Builder mergeMove(orwell.messages.Robot.RobotState.Move value) {
        if (((bitField0_ & 0x00000002) == 0x00000002) &&
            move_ != orwell.messages.Robot.RobotState.Move.getDefaultInstance()) {
          move_ =
            orwell.messages.Robot.RobotState.Move.newBuilder(move_).mergeFrom(value).buildPartial();
        } else {
          move_ = value;
        }

        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional group Move = 2 { ... }</code>
       */
      public Builder clearMove() {
        move_ = orwell.messages.Robot.RobotState.Move.getDefaultInstance();

        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      // optional bool active = 3 [default = true];
      private boolean active_ = true;
      /**
       * <code>optional bool active = 3 [default = true];</code>
       */
      public boolean hasActive() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool active = 3 [default = true];</code>
       */
      public boolean getActive() {
        return active_;
      }
      /**
       * <code>optional bool active = 3 [default = true];</code>
       */
      public Builder setActive(boolean value) {
        bitField0_ |= 0x00000004;
        active_ = value;
        
        return this;
      }
      /**
       * <code>optional bool active = 3 [default = true];</code>
       */
      public Builder clearActive() {
        bitField0_ = (bitField0_ & ~0x00000004);
        active_ = true;
        
        return this;
      }

      // optional string rfid = 4 [default = ""];
      private java.lang.Object rfid_ = "";
      /**
       * <code>optional string rfid = 4 [default = ""];</code>
       */
      public boolean hasRfid() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string rfid = 4 [default = ""];</code>
       */
      public java.lang.String getRfid() {
        java.lang.Object ref = rfid_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          rfid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string rfid = 4 [default = ""];</code>
       */
      public com.google.protobuf.ByteString
          getRfidBytes() {
        java.lang.Object ref = rfid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          rfid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string rfid = 4 [default = ""];</code>
       */
      public Builder setRfid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        rfid_ = value;
        
        return this;
      }
      /**
       * <code>optional string rfid = 4 [default = ""];</code>
       */
      public Builder clearRfid() {
        bitField0_ = (bitField0_ & ~0x00000008);
        rfid_ = getDefaultInstance().getRfid();
        
        return this;
      }
      /**
       * <code>optional string rfid = 4 [default = ""];</code>
       */
      public Builder setRfidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        rfid_ = value;
        
        return this;
      }

      // optional int32 color = 5 [default = -1];
      private int color_ = -1;
      /**
       * <code>optional int32 color = 5 [default = -1];</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional int32 color = 5 [default = -1];</code>
       */
      public int getColor() {
        return color_;
      }
      /**
       * <code>optional int32 color = 5 [default = -1];</code>
       */
      public Builder setColor(int value) {
        bitField0_ |= 0x00000010;
        color_ = value;
        
        return this;
      }
      /**
       * <code>optional int32 color = 5 [default = -1];</code>
       */
      public Builder clearColor() {
        bitField0_ = (bitField0_ & ~0x00000010);
        color_ = -1;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:orwell.messages.RobotState)
    }

    static {
      defaultInstance = new RobotState(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:orwell.messages.RobotState)
  }

  public interface RegisterOrBuilder
      extends com.google.protobuf.MessageLiteOrBuilder {

    // required string temporary_robot_id = 1;
    /**
     * <code>required string temporary_robot_id = 1;</code>
     *
     * <pre>
     * this temporary robot ID is only used when registering because
     * we do not know yet what ID the server will assign to the robot
     * </pre>
     */
    boolean hasTemporaryRobotId();
    /**
     * <code>required string temporary_robot_id = 1;</code>
     *
     * <pre>
     * this temporary robot ID is only used when registering because
     * we do not know yet what ID the server will assign to the robot
     * </pre>
     */
    java.lang.String getTemporaryRobotId();
    /**
     * <code>required string temporary_robot_id = 1;</code>
     *
     * <pre>
     * this temporary robot ID is only used when registering because
     * we do not know yet what ID the server will assign to the robot
     * </pre>
     */
    com.google.protobuf.ByteString
        getTemporaryRobotIdBytes();

    // required string video_url = 2;
    /**
     * <code>required string video_url = 2;</code>
     */
    boolean hasVideoUrl();
    /**
     * <code>required string video_url = 2;</code>
     */
    java.lang.String getVideoUrl();
    /**
     * <code>required string video_url = 2;</code>
     */
    com.google.protobuf.ByteString
        getVideoUrlBytes();

    // required string image = 3;
    /**
     * <code>required string image = 3;</code>
     */
    boolean hasImage();
    /**
     * <code>required string image = 3;</code>
     */
    java.lang.String getImage();
    /**
     * <code>required string image = 3;</code>
     */
    com.google.protobuf.ByteString
        getImageBytes();
  }
  /**
   * Protobuf type {@code orwell.messages.Register}
   *
   * <pre>
   * Ask the server to register a new robot. The video address and port
   * are provided.
   * Answered by: Registered
   * </pre>
   */
  public static final class Register extends
      com.google.protobuf.GeneratedMessageLite
      implements RegisterOrBuilder {
    // Use Register.newBuilder() to construct.
    private Register(com.google.protobuf.GeneratedMessageLite.Builder builder) {
      super(builder);

    }
    private Register(boolean noInit) {}

    private static final Register defaultInstance;
    public static Register getDefaultInstance() {
      return defaultInstance;
    }

    public Register getDefaultInstanceForType() {
      return defaultInstance;
    }

    private Register(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              temporaryRobotId_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              videoUrl_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              image_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static com.google.protobuf.Parser<Register> PARSER =
        new com.google.protobuf.AbstractParser<Register>() {
      public Register parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Register(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Register> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string temporary_robot_id = 1;
    public static final int TEMPORARY_ROBOT_ID_FIELD_NUMBER = 1;
    private java.lang.Object temporaryRobotId_;
    /**
     * <code>required string temporary_robot_id = 1;</code>
     *
     * <pre>
     * this temporary robot ID is only used when registering because
     * we do not know yet what ID the server will assign to the robot
     * </pre>
     */
    public boolean hasTemporaryRobotId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string temporary_robot_id = 1;</code>
     *
     * <pre>
     * this temporary robot ID is only used when registering because
     * we do not know yet what ID the server will assign to the robot
     * </pre>
     */
    public java.lang.String getTemporaryRobotId() {
      java.lang.Object ref = temporaryRobotId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          temporaryRobotId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string temporary_robot_id = 1;</code>
     *
     * <pre>
     * this temporary robot ID is only used when registering because
     * we do not know yet what ID the server will assign to the robot
     * </pre>
     */
    public com.google.protobuf.ByteString
        getTemporaryRobotIdBytes() {
      java.lang.Object ref = temporaryRobotId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        temporaryRobotId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string video_url = 2;
    public static final int VIDEO_URL_FIELD_NUMBER = 2;
    private java.lang.Object videoUrl_;
    /**
     * <code>required string video_url = 2;</code>
     */
    public boolean hasVideoUrl() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string video_url = 2;</code>
     */
    public java.lang.String getVideoUrl() {
      java.lang.Object ref = videoUrl_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          videoUrl_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string video_url = 2;</code>
     */
    public com.google.protobuf.ByteString
        getVideoUrlBytes() {
      java.lang.Object ref = videoUrl_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        videoUrl_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required string image = 3;
    public static final int IMAGE_FIELD_NUMBER = 3;
    private java.lang.Object image_;
    /**
     * <code>required string image = 3;</code>
     */
    public boolean hasImage() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string image = 3;</code>
     */
    public java.lang.String getImage() {
      java.lang.Object ref = image_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          image_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string image = 3;</code>
     */
    public com.google.protobuf.ByteString
        getImageBytes() {
      java.lang.Object ref = image_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        image_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      temporaryRobotId_ = "";
      videoUrl_ = "";
      image_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasTemporaryRobotId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasVideoUrl()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasImage()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getTemporaryRobotIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getVideoUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getImageBytes());
      }
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getTemporaryRobotIdBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getVideoUrlBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getImageBytes());
      }
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static orwell.messages.Robot.Register parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static orwell.messages.Robot.Register parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static orwell.messages.Robot.Register parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static orwell.messages.Robot.Register parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static orwell.messages.Robot.Register parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static orwell.messages.Robot.Register parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static orwell.messages.Robot.Register parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static orwell.messages.Robot.Register parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static orwell.messages.Robot.Register parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static orwell.messages.Robot.Register parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(orwell.messages.Robot.Register prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    /**
     * Protobuf type {@code orwell.messages.Register}
     *
     * <pre>
     * Ask the server to register a new robot. The video address and port
     * are provided.
     * Answered by: Registered
     * </pre>
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          orwell.messages.Robot.Register, Builder>
        implements orwell.messages.Robot.RegisterOrBuilder {
      // Construct using orwell.messages.Robot.Register.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private void maybeForceBuilderInitialization() {
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        temporaryRobotId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        videoUrl_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        image_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public orwell.messages.Robot.Register getDefaultInstanceForType() {
        return orwell.messages.Robot.Register.getDefaultInstance();
      }

      public orwell.messages.Robot.Register build() {
        orwell.messages.Robot.Register result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public orwell.messages.Robot.Register buildPartial() {
        orwell.messages.Robot.Register result = new orwell.messages.Robot.Register(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.temporaryRobotId_ = temporaryRobotId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.videoUrl_ = videoUrl_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.image_ = image_;
        result.bitField0_ = to_bitField0_;
        return result;
      }

      public Builder mergeFrom(orwell.messages.Robot.Register other) {
        if (other == orwell.messages.Robot.Register.getDefaultInstance()) return this;
        if (other.hasTemporaryRobotId()) {
          bitField0_ |= 0x00000001;
          temporaryRobotId_ = other.temporaryRobotId_;
          
        }
        if (other.hasVideoUrl()) {
          bitField0_ |= 0x00000002;
          videoUrl_ = other.videoUrl_;
          
        }
        if (other.hasImage()) {
          bitField0_ |= 0x00000004;
          image_ = other.image_;
          
        }
        return this;
      }

      public final boolean isInitialized() {
        if (!hasTemporaryRobotId()) {
          
          return false;
        }
        if (!hasVideoUrl()) {
          
          return false;
        }
        if (!hasImage()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        orwell.messages.Robot.Register parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (orwell.messages.Robot.Register) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string temporary_robot_id = 1;
      private java.lang.Object temporaryRobotId_ = "";
      /**
       * <code>required string temporary_robot_id = 1;</code>
       *
       * <pre>
       * this temporary robot ID is only used when registering because
       * we do not know yet what ID the server will assign to the robot
       * </pre>
       */
      public boolean hasTemporaryRobotId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string temporary_robot_id = 1;</code>
       *
       * <pre>
       * this temporary robot ID is only used when registering because
       * we do not know yet what ID the server will assign to the robot
       * </pre>
       */
      public java.lang.String getTemporaryRobotId() {
        java.lang.Object ref = temporaryRobotId_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          temporaryRobotId_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string temporary_robot_id = 1;</code>
       *
       * <pre>
       * this temporary robot ID is only used when registering because
       * we do not know yet what ID the server will assign to the robot
       * </pre>
       */
      public com.google.protobuf.ByteString
          getTemporaryRobotIdBytes() {
        java.lang.Object ref = temporaryRobotId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          temporaryRobotId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string temporary_robot_id = 1;</code>
       *
       * <pre>
       * this temporary robot ID is only used when registering because
       * we do not know yet what ID the server will assign to the robot
       * </pre>
       */
      public Builder setTemporaryRobotId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        temporaryRobotId_ = value;
        
        return this;
      }
      /**
       * <code>required string temporary_robot_id = 1;</code>
       *
       * <pre>
       * this temporary robot ID is only used when registering because
       * we do not know yet what ID the server will assign to the robot
       * </pre>
       */
      public Builder clearTemporaryRobotId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        temporaryRobotId_ = getDefaultInstance().getTemporaryRobotId();
        
        return this;
      }
      /**
       * <code>required string temporary_robot_id = 1;</code>
       *
       * <pre>
       * this temporary robot ID is only used when registering because
       * we do not know yet what ID the server will assign to the robot
       * </pre>
       */
      public Builder setTemporaryRobotIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        temporaryRobotId_ = value;
        
        return this;
      }

      // required string video_url = 2;
      private java.lang.Object videoUrl_ = "";
      /**
       * <code>required string video_url = 2;</code>
       */
      public boolean hasVideoUrl() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string video_url = 2;</code>
       */
      public java.lang.String getVideoUrl() {
        java.lang.Object ref = videoUrl_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          videoUrl_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string video_url = 2;</code>
       */
      public com.google.protobuf.ByteString
          getVideoUrlBytes() {
        java.lang.Object ref = videoUrl_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          videoUrl_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string video_url = 2;</code>
       */
      public Builder setVideoUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        videoUrl_ = value;
        
        return this;
      }
      /**
       * <code>required string video_url = 2;</code>
       */
      public Builder clearVideoUrl() {
        bitField0_ = (bitField0_ & ~0x00000002);
        videoUrl_ = getDefaultInstance().getVideoUrl();
        
        return this;
      }
      /**
       * <code>required string video_url = 2;</code>
       */
      public Builder setVideoUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        videoUrl_ = value;
        
        return this;
      }

      // required string image = 3;
      private java.lang.Object image_ = "";
      /**
       * <code>required string image = 3;</code>
       */
      public boolean hasImage() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string image = 3;</code>
       */
      public java.lang.String getImage() {
        java.lang.Object ref = image_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          image_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string image = 3;</code>
       */
      public com.google.protobuf.ByteString
          getImageBytes() {
        java.lang.Object ref = image_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          image_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string image = 3;</code>
       */
      public Builder setImage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        image_ = value;
        
        return this;
      }
      /**
       * <code>required string image = 3;</code>
       */
      public Builder clearImage() {
        bitField0_ = (bitField0_ & ~0x00000004);
        image_ = getDefaultInstance().getImage();
        
        return this;
      }
      /**
       * <code>required string image = 3;</code>
       */
      public Builder setImageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        image_ = value;
        
        return this;
      }

      // @@protoc_insertion_point(builder_scope:orwell.messages.Register)
    }

    static {
      defaultInstance = new Register(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:orwell.messages.Register)
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
